[workspace]
resolver = "2"
members = [
    "examples/rocket-chat",
    "impls/server/rust"
]

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = [
    "Матвей Т <https://matveit.dev> AtomicGamer9523@github"
]